language: bash

before_script:
  - git clone https://github.com/callumacrae/if_changed.git
  - cd if_changed
  - git config user.email callum@travis
  - git config user.name "travis test"
  - git merge -m "merge" origin/test

script:
  - bash test.sh
